baseURL = "https://hnu6051.gitpages.huma-num.fr/modele2/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Titre"
theme = "cupper-hugo-theme"
enableGitInfo = true

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:filename/"

[imaging]
quality = 99

[params]
description = "description"
homeMetaContent = ""
footer = "Texte du footer"
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = true
defaultDarkTheme = false
moveFooterToHeader = false
logoAlt = "Description si le logo ne s'affiche pas"
customCss = [ "css/custom_01.css", "css/custom_02.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]

[[menu.nav]]
name = "Accueil"
url = "/"
weight = 1

[[menu.nav]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.nav]]
name = "Documentation"
url = "/docs/"
weight = 3

[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.nav]]
name = "Ã€ propos"
url = "/about/"
weight = 5

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2
